version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-obuspartners/obus-partner-api}:latest
    container_name: obus-partner-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE:-prod}
      - JAVA_OPTS=-XX:+UseZGC -XX:+ZGenerational -XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=30.0 -XX:MetaspaceSize=192m -XX:MaxMetaspaceSize=384m
    env_file:
      - .env.${PROFILE:-prod}
    volumes:
      - ./logs:/app/logs
    networks:
      - obus-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1.5G

  redis:
    image: redis:7-alpine
    container_name: obus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - obus-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: obus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - obus-network
    depends_on:
      - app

volumes:
  redis-data:
    driver: local

networks:
  obus-network:
    driver: bridge
