version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: obus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - obus-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: obus-redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    restart: unless-stopped
    networks:
      - obus-network
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  obus-network:
    driver: bridge
