# Application Configuration
spring:
  application:
    name: obus-partner-api
  datasource:
    url: jdbc:mysql://localhost:3306/obus_partner_db_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,resources/**
    livereload:
      enabled: true
      port: 35729
    remote:
      restart:
        enabled: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.obus.partner: DEBUG
    org.springframework.web: DEBUG

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true

# JWT Configuration
jwt:
  secret: a8f5f167f44f4964e6c998dee827110c8f5f167f44f4964e6c998dee827110c8f5f167f44f4964e6c998dee827110c8f5f167f44f4964e6c998dee827110c
  expiration: 36000 # 10 hours in seconds
  refresh-expiration: 604800 # 7 days in seconds

# Root Admin Configuration
root-admin:
  username: rootadmin
  password: Root@2024!Sec
  email: rootadmin@obus.com
  firstName: Root
  lastName: Administrator